import = ["/home/burgues/.config/alacritty/themes/blood_moon.toml"]

[font.normal]
family = "monospace"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[window]
decorations_theme_variant = "Dark"
dynamic_title = false
opacity = 0.85
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 7
y = 7
